name: agrischield_ai
description: "AgriShield AI - L'IA veille sur vos cultures"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36

  # Navigation
  go_router: ^13.0.0

  # State Management
  flutter_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0

  # UI & Animations
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

  # Camera & Image
  camera: ^0.10.0
  image_picker: ^1.0.0
  path_provider: ^2.1.0

  # Maps
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2

  # Utilities
  intl: ^0.19.0
  permission_handler: ^11.0.0
  share_plus: ^7.0.0
  url_launcher: ^6.1.0
  device_info_plus: ^9.0.0

  # Storage
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0

  # Network
  dio: ^5.3.0
  connectivity_plus: ^5.0.0

  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # Icons
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.0
  build_runner: ^2.4.0
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/

