name: agrischield_ai
description: "AgriShield AI - L'IA veille sur vos cultures"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36

  # Navigation
  go_router: ^16.0.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # UI & Animations
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0

  # Camera & Image
  camera: ^0.11.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2

  # Maps
  google_maps_flutter: ^2.6.1
  geolocator: ^14.0.2

  # Utilities
  intl: ^0.20.2
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  url_launcher: ^6.2.5
  device_info_plus: ^11.5.0

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2

  # Network
  dio: ^5.4.1
  connectivity_plus: ^6.1.4

  # PDF
  pdf: ^3.10.8
  printing: ^5.12.0

  # Icons
  cupertino_icons: ^1.0.8
  phosphor_flutter: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.7.5
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/audio/

